name: Python Hola Mundo

on:
  push:
    branches: [ actions-tryouts ]

jobs:
    python:
      runs-on: ubuntu-latest
      
      steps:
        - name: check python
          run: |
            python -c "print('Hola Mundo')"
            python --version
